version: "3.8"
   
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=DataParserToDB
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=e30be82d1bc8bce929501701a738b93e0315f8e7c9825941a62cb64b154db0a4
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"

  app:
    build: .
    image: &img app:latest
    command: sh -c "python3 manage.py app"
    volumes:
      - .:/opt/DataParserToDB/DataParser/data
    links:
      - db
      - redis
    depends_on:
      - migration
      - redis

  migration:
    build: .
    image: *img
    command: sh -c "
              python3 manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py makemigrations &&
               python manage.py migrate"
    volumes:
      - .:/opt/DataParserToDB/DataParser/data
    links:
      - db
    depends_on:
      - db

  workers:
    build: .
    image: *img
    command: celery -A DataParser worker -l info -B
    links:
      - app
      - redis
    depends_on:
      - app
      - redis
